// Fetches official statistics and bakes them into src/generated/seriesData.ts.
//
// Runs in CI (which has internet) before `vite build`. Each source is isolated
// in try/catch and the script NEVER fails the build — any source that errors is
// skipped and the app keeps its bundled illustrative fallback for that series.
// The repo commits an EMPTY object, so no datasets live in git; CI overwrites
// this file for the production build only.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const OUT = "src/generated/seriesData.ts";

const MONTHS = {
  JAN: 1, FEB: 2, MAR: 3, APR: 4, MAY: 5, JUN: 6,
  JUL: 7, AUG: 8, SEP: 9, OCT: 10, NOV: 11, DEC: 12,
};

function onsDate(o) {
  const d = String(o.date || "").trim().toUpperCase();
  let m;
  if ((m = d.match(/^(\d{4})\s+([A-Z]{3})$/)))
    return `${m[1]}-${String(MONTHS[m[2]] ?? 1).padStart(2, "0")}-01`;
  if ((m = d.match(/^(\d{4})\s+Q(\d)$/)))
    return `${m[1]}-${String((+m[2] - 1) * 3 + 1).padStart(2, "0")}-01`;
  if ((m = d.match(/^(\d{4})$/))) return `${m[1]}-01-01`;
  return null;
}

// ONS publishes JSON for any time series by appending /data to its page URL:
// https://www.ons.gov.uk/{topic}/timeseries/{cdid}/{dataset}/data
async function ons(topic, cdid, dataset, freq = "years") {
  const url = `https://www.ons.gov.uk/${topic}/timeseries/${cdid.toLowerCase()}/${dataset.toLowerCase()}/data`;
  const res = await fetch(url, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`${cdid}/${dataset} → HTTP ${res.status} (${url})`);
  const j = await res.json();
  let arr = j[freq] || [];
  if (!arr.length) arr = j.quarters || j.months || [];
  const points = arr
    .map((o) => ({ date: onsDate(o), value: Number(o.value) }))
    .filter((p) => p.date && Number.isFinite(p.value));
  if (!points.length) throw new Error(`${cdid}/${dataset}: no usable points`);
  return points;
}

const INFLATION = "economy/inflationandpriceindices";
const PUBFIN = "economy/governmentpublicsectorandtaxes/publicsectorfinance";

// Manifest. `id` = TrendSeries id; `line` = which line of a multi-line chart.
// CDIDs are best-effort and verified/iterated against CI fetch logs.
const SOURCES = [
  // CPI 12-month inflation rate → the CPI line of the cost-of-living chart.
  { id: "hmt-cost-of-living", line: "cpi", get: () => ons(INFLATION, "D7G7", "mm23", "years") },
  // Public sector net debt (ex public sector banks) as % of GDP.
  { id: "hmt-psnd", get: () => ons(PUBFIN, "HF6X", "pusf", "years") },
  // Public sector net debt (ex banks) cash level, £mn → stored as £bn.
  { id: "hmt-psnd-cash", scale: 1 / 1000, get: () => ons(PUBFIN, "HF6W", "pusf", "years") },
];

const out = {};
let ok = 0;
let fail = 0;
for (const s of SOURCES) {
  const tag = `${s.id}${s.line ? ":" + s.line : ""}`;
  try {
    let points = await s.get();
    if (s.scale) points = points.map((p) => ({ date: p.date, value: p.value * s.scale }));
    out[s.id] ??= {};
    if (s.line) (out[s.id].lines ??= []).push({ id: s.line, points });
    else out[s.id].points = points;
    out[s.id].asOf = new Date().toISOString().slice(0, 10);
    ok++;
    console.log(
      `ok   ${tag}  ${points.length} pts  ${points[0].date}..${points[points.length - 1].date}`,
    );
  } catch (e) {
    fail++;
    console.warn(`SKIP ${tag}  ${e.message}`);
  }
}

const file =
  `// AUTO-GENERATED by scripts/build-data.mjs — do not edit or commit populated data.\n` +
  `export type RawPoint = { date: string; value: number };\n` +
  `export type RawSeries = { points?: RawPoint[]; lines?: { id: string; points: RawPoint[] }[]; asOf?: string };\n` +
  `export const SERIES_DATA: Record<string, RawSeries> = ${JSON.stringify(out, null, 2)};\n`;
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, file);
console.log(`\nwrote ${OUT}: ${ok} ok, ${fail} skipped`);
process.exit(0); // never fail the build over data fetching
