/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeptRouteImport } from './routes/$dept'
import { Route as IndexRouteImport } from './routes/index'

const DeptRoute = DeptRouteImport.update({
  id: '/$dept',
  path: '/$dept',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$dept': typeof DeptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$dept': typeof DeptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$dept': typeof DeptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$dept'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$dept'
  id: '__root__' | '/' | '/$dept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeptRoute: typeof DeptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$dept': {
      id: '/$dept'
      path: '/$dept'
      fullPath: '/$dept'
      preLoaderRoute: typeof DeptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeptRoute: DeptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
