/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as DataRouteImport } from './routes/data'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DeptRouteImport } from './routes/$dept'
import { Route as IndexRouteImport } from './routes/index'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptRoute = DeptRouteImport.update({
  id: '/$dept',
  path: '/$dept',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$dept': typeof DeptRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/data': typeof DataRoute
  '/overview': typeof OverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$dept': typeof DeptRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/data': typeof DataRoute
  '/overview': typeof OverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$dept': typeof DeptRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/data': typeof DataRoute
  '/overview': typeof OverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$dept' | '/about' | '/blog' | '/data' | '/overview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$dept' | '/about' | '/blog' | '/data' | '/overview'
  id: '__root__' | '/' | '/$dept' | '/about' | '/blog' | '/data' | '/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeptRoute: typeof DeptRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  DataRoute: typeof DataRoute
  OverviewRoute: typeof OverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$dept': {
      id: '/$dept'
      path: '/$dept'
      fullPath: '/$dept'
      preLoaderRoute: typeof DeptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeptRoute: DeptRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  DataRoute: DataRoute,
  OverviewRoute: OverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
